export { default as About } from './About'
export { default as Technologies } from './Technologies'
export { default as Project } from './Project'
export { default as Education } from './Education'
export { default as Contact } from './Contact'
export { default as Story } from './Story'